[runtime]
parameter_txt = "trial_2_parameters.txt"

[data]
network = "II"
station = "BFO"
channel = "LHZ"
location = "00"
stream_index = 0
start_time = "2025-07-30T01:24:50"
end_time = "2025-08-05T20:24:50"
min_f = 0.003
max_f = 0.004

[model]
f_min = 0.0027
f_max = 0.0043
k_min = 1e-5
k_max = 1e-4
path = "trial_2"

[grid_search]
f_points = 200
k_points = 200

[nuts.sample.nuts_kwargs]
target_accept_prob = 0.8

[nuts.sample.mcmc_kwargs]
num_warmup = 200
num_samples = 400
num_chains = 4
chain_method = "parallel"

[nuts.sample.run_kwargs]

[nuts.sample]
seed = 1

[nuts.reconcile.nuts_kwargs]
target_accept_prob = 0.8
max_tree_depth = [5, 5]

[nuts.reconcile.mcmc_kwargs]
num_warmup = 200
num_samples = 400
num_chains = 4
chain_method = "parallel"

[nuts.reconcile.run_kwargs]

[nuts.reconcile]
seed = 1

[execute]
subband_count = 4
subband_scaling_factor = 1.0
f_fraction = 12
log_k_fraction = 4
depth = 15
cores_per_initial_conditions_worker = 1
signals_per_block = 20
fill_order = 0
cores_per_sample_worker = 4
k2_threshold = 30
cores_per_reconcile_worker = 4
perform_minimize = false
